---
title: "PCA_Thesis"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=F, include=TRUE}
#install.packages(c("FactoMineR", "factoextra"))
#install.packages("colorspace", dependencies = TRUE)
library("FactoMineR")
library("factoextra")
library("tidyr")
library("tidyverse")
library("haven")

read_sav("~/Dropbox/BSHS/Thesis Prep/Dataset/rgthesisic.sav") -> rgthesisic
rgthesisic <- data.frame(rgthesisic)
#We start by subsetting active individuals and active variables for the principal component analysis:

pcaset<- rgthesisic[which(!is.na(rowSums(rgthesisic))),1:23]

PCA(pcaset, scale.unit = TRUE, ncp = 5, graph = TRUE)

library("FactoMineR")
res.pca <- PCA(pcaset, graph = FALSE)
print(res.pca)

library("factoextra")
eig.val <- get_eigenvalue(res.pca)
eig.val

fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 50))

var <- get_pca_var(res.pca)
var

# Total cos2 of variables on Dim.1 and Dim.2
fviz_cos2(res.pca, choice = "var", axes = 1:2)

# Color by cos2 values: quality on the factor map
fviz_pca_var(res.pca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )


#The most important (or, contributing) variables can be highlighted on the correlation plot as follow:

fviz_pca_var(res.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")
             )
```

